name: Deploy Explorer
description: Build and deploy the Hathor Explorer to AWS

inputs:
  site:
    description: The site name to build and deploy (e.g., testnet, mainnet, nano-testnet-bravo)
    required: true
  aws-region:
    description: The AWS region to deploy to
    required: true
    default: us-east-1
  aws-role:
    description: The AWS IAM role to assume for deployment
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      # https://github.com/aws-actions/configure-aws-credentials/releases/tag/v4.2.1
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role }}

    - name: Download node modules
      # https://github.com/actions/download-artifact/releases/tag/v4.3.0
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        name: node_modules

    - name: Build
      shell: bash
      run: |
        tar -xf node_modules.tar
        make build site=${{ inputs.site }}

    - name: Deploy
      shell: bash
      run: |
        make deploy site=${{ inputs.site }}
