name: PR validation

on:
  push:
    branches: [master, release]
  pull_request:
    branches:
    - release
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.1.7
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node/releases/tag/v4.0.3
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          make build site=testnet

      - name: Format
        run: |
          npm run format:check

      - name: Linting
        run: |
          npm run lint
